# Generated by Django 3.2.16 on 2023-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='images/book')),
                ('kitob_nomi', models.CharField(max_length=100)),
                ('describtion', models.TextField(help_text='Kitob haqida malumot')),
                ('kitob_pdf', models.FileField(help_text='Kitobni kiriting', upload_to='pdf/book')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
